-- =========================================================================
-- SCRIPT DI MIGRAZIONE: Aggiunta nuovi campi API
-- Esegui questo script nello "SQL Editor" di Supabase
-- =========================================================================

ALTER TABLE allievi 
    ADD COLUMN IF NOT EXISTS data_nascita TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS codice_fiscale TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS comune_nascita TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS cognome_referente TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS nome_referente TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS email TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS recapiti_telefonici TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS annualita TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gruppo TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS id_preiscrizione TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS tipologia TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS num_turni TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS num_gite TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS turno1 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gita1 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS turno2 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gita2 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS turno3 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gita3 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS turno4 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gita4 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS turno5 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gita5 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS turno6 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gita6 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS turno7 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gita7 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS turno8 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gita8 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS turno9 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gita9 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS turno10 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gita10 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS turno11 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gita11 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS turno12 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gita12 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS turno13 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gita13 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS turno14 TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS gita14 TEXT DEFAULT '';

-- Ricarica la cache per rendere visibili le nuove colonne
NOTIFY pgrst, 'reload schema';
